---
# This file is used by developers who use ./scripts/deploy.sh to set up a local
# development environment to help with development this module.
version: '2'

services:
  drupal:
    image: dcycle/drupal:9php8
    volumes:
      - ".:/var/www/html/modules/custom/eventbrite_one_way_sync"
    ports:
      - "80"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'

# Specifying the network name makes it predictable on all environments,
# for example when we run browser tests.
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: eventbrite_one_way_sync_default
