---
# This file is used by developers who use ./scripts/deploy.sh to set up a local
# development environment to help with development this module.
version: '3'

services:
  drupal:
    image: dcycle/drupal:9php8
    volumes:
      - ".:/var/www/html/modules/custom/eventbrite_one_way_sync"
    ports:
      - "80"
    links:
      - mysql:mysql
    working_dir: /var/www/html

  mysql:
    image: mariadb
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'

  dummy_server:
    build:
      context: .
      dockerfile: ./scripts/lib/dummy-eventbrite-server/Dockerfile
    ports:
      - "80"
    volumes:
      - "./scripts/lib/dummy-eventbrite-server/www:/var/www/html/"
      - "./scripts/lib/dummy-eventbrite-server/mod_rewrite.conf:/etc/apache2/sites-enabled/mod_rewrite.conf"

# Specifying the network name makes it predictable on all environments,
# for example when we run browser tests.
# See https://github.com/docker/compose/issues/3736.
networks:
  default:
    external:
      name: eventbrite_one_way_sync_default
